name: case_test
description: Starter
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  # Logger
  l: ^4.0.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  meta: any
  platform_info: ^4.0.2
  dio: ^5.4.1
  uuid: ^4.3.3

  # Kassa
  yookassa_payments_flutter: ^1.3.0

  # Codegen
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

  # Navigation
  go_router: ^10.0.0

  # Desktop
  window_manager: ^0.3.5

  # Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0

  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3
  provider: ^6.0.5

  # JSON
  json_annotation: ^4.8.1

  # Network
  grpc: ^3.2.3
  protobuf: ^3.0.0
  jwt_decoder: ^2.0.1

  # Assets / Images
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

  # Typography
  google_fonts: ^5.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  # Codegen
  build_runner: ^2.4.6

  # JSON
  json_serializable: ^6.7.1

  # App Icon / Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "assets/images/splash_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/main/
    - assets/images/svg/
    - assets/fonts/
  # fonts:
  #   - family: Kitab
  #     fonts:
  #       - asset: assets/fonts/Kitab-Regular.ttf
  #   - family: Uthmanic
  #     fonts:
  #       - asset: assets/fonts/Uthmanic-Regular.otf

# Localization settings
flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/app/localization
  output_dir: lib/src/app/localization/generated
  use_deferred_loading: false
